require('dotenv').config();
const express = require('express');
const connectDB = require('./db');
const app = express();
connectDB();
app.use(express.json());
app.use('/api', require('./routes/authRoutes'));
app.use('/api', require('./routes/sessionRoutes'));
app.get('/', (_, res) => res.send('API Running'));
app.listen(process.env.PORT || 5000, () => console.log('Server started'));
